"use client"

import { useEffect, useState, Suspense } from "react"
import { useSearchParams, useRouter } from "next/navigation"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Loader2, ArrowLeft, Columns, CheckCircle2 } from "lucide-react"
import { SiteHeader } from "@/components/site-header"

type ScrumTicket = {
    title: string
    description: string
    status?: "to do" | "in progress" | "done"
    assignee?: string
    priority?: "low" | "medium" | "high"
    tags?: string[]
}

import { ClickUpIntegration } from "@/components/scrum/clickup-integration"
import { Dialog, DialogContent, DialogTrigger, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog"
import { useToast } from "@/components/ui/use-toast"
import { apiFetch } from "@/lib/api"

function ScrumBoardContent() {
    const router = useRouter()
    const searchParams = useSearchParams()
    const botId = searchParams.get("botId")
    const { toast } = useToast()

    const [tickets, setTickets] = useState<ScrumTicket[]>([])
    const [loading, setLoading] = useState(true)
    const [error, setError] = useState("")
    const [isIntegrationOpen, setIsIntegrationOpen] = useState(false)
    const [isPushing, setIsPushing] = useState(false)

    useEffect(() => {
        if (!botId) {
            setError("No meeting ID provided")
            setLoading(false)
            return
        }

        const fetchTickets = async () => {
            try {
                setError("")
                setLoading(true)
                const data = await apiFetch(`/meeting-transcripts?bot_id=${botId}&mode=scrum&format=json&auto_process=true`)
                console.log("Scrum data:", data)

                // Handle different response structures
                const items = Array.isArray(data) ? data : (data.tickets || data.items || [])
                setTickets(items)
            } catch (err: any) {
                console.error(err)
                if (err.message?.includes("No transcripts found") || err.message?.includes("not found")) {
                    setError("Scrum tickets are still being generated by AI. Please wait a few seconds and try again.")
                } else {
                    setError("Failed to load scrum tickets. Make sure the meeting has ended.")
                }
            } finally {
                setLoading(false)
            }
        }

        fetchTickets()
    }, [botId])

    const getPriorityColor = (p?: string) => {
        switch (p?.toLowerCase()) {
            case 'high': return 'bg-red-500/10 text-red-500 hover:bg-red-500/20'
            case 'medium': return 'bg-yellow-500/10 text-yellow-500 hover:bg-yellow-500/20'
            case 'low': return 'bg-green-500/10 text-green-500 hover:bg-green-500/20'
            default: return 'bg-slate-500/10 text-slate-500 hover:bg-slate-500/20'
        }
    }

    const mapPriority = (p?: string): number => {
        switch (p?.toLowerCase()) {
            case 'urgent': return 1
            case 'high': return 2
            case 'medium': return 3
            case 'low': return 4
            default: return 3 // Normal
        }
    }

    const handlePushTickets = async (listId: string, token: string, assigneeId?: string) => {
        setIsIntegrationOpen(false)
        setIsPushing(true)

        let successCount = 0
        let failCount = 0

        toast({
            title: "Pushing tickets to ClickUp...",
            description: `Starting export of ${tickets.length} tickets.`,
        })

        for (const ticket of tickets) {
            try {
                const body: any = {
                    list_id: listId,
                    name: ticket.title,
                    description: ticket.description,
                    priority: mapPriority(ticket.priority),
                    status: ticket.status || "to do",
                    tags: ticket.tags || [],
                }

                // Add assignee if selected
                if (assigneeId) {
                    body.assignees = [parseInt(assigneeId) || assigneeId] // Try parsing to int as ClickUp uses ints for user IDs typically, but valid string is generic
                }

                const res = await fetch(`/api/clickup/task?token=${token}`, {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify(body)
                })

                if (!res.ok) {
                    console.error("Failed to push ticket:", ticket.title, await res.text())
                    failCount++
                } else {
                    successCount++
                }
            } catch (error) {
                console.error("Error pushing ticket:", error)
                failCount++
            }
        }

        setIsPushing(false)

        if (successCount > 0) {
            toast({
                title: "Export Complete",
                description: `Successfully pushed ${successCount} tickets to ClickUp.${failCount > 0 ? ` (${failCount} failed)` : ''}`,
                variant: failCount > 0 ? "destructive" : "default", // Use destructive style if partial failure? Or maybe just default. default is usually fine for success.
                // Let's use destructive only if ALL failed, or maybe add a warning style if mixed.
                // shadcn toast usually has default | destructive.
                className: "bg-green-900 border-green-800 text-green-100" // Custom style for success
            })
        } else if (failCount > 0) {
            toast({
                title: "Export Failed",
                description: "Failed to push any tickets to ClickUp. Check console for details.",
                variant: "destructive"
            })
        }
    }

    return (
        <div className="min-h-screen bg-slate-950 text-white">
            <SiteHeader />

            <main className="container mx-auto p-6 max-w-7xl">
                <div className="flex items-center justify-between mb-8">
                    <div className="flex items-center gap-4">
                        <Button variant="ghost" className="text-slate-400" onClick={() => router.push("/start-meeting")}>
                            <ArrowLeft className="w-4 h-4 mr-2" />
                            Back
                        </Button>
                        <div>
                            <h1 className="text-2xl font-bold flex items-center gap-2">
                                <Columns className="w-6 h-6 text-blue-500" />
                                Scrum Board
                            </h1>
                            <p className="text-slate-400 text-sm">Generated from meeting transcript</p>
                        </div>
                    </div>

                    <Dialog open={isIntegrationOpen} onOpenChange={setIsIntegrationOpen}>
                        <DialogTrigger asChild>
                            <Button
                                className="bg-[#7b68ee] hover:bg-[#6c5ce7] text-white"
                            >
                                <img src="https://clickup.com/landing/images/logo-clickup_color.svg" alt="ClickUp" className="w-4 h-4 mr-2 filter brightness-0 invert" />
                                Commit to ClickUp
                            </Button>
                        </DialogTrigger>
                        <DialogContent className="bg-transparent border-none p-0 max-w-lg shadow-none">
                            <DialogHeader className="sr-only">
                                <DialogTitle>ClickUp Integration</DialogTitle>
                                <DialogDescription>Connect and export tickets to ClickUp</DialogDescription>
                            </DialogHeader>
                            <ClickUpIntegration
                                onCancel={() => setIsIntegrationOpen(false)}
                                onCommit={handlePushTickets}
                            />
                        </DialogContent>
                    </Dialog>
                </div>

                {loading ? (
                    <div className="flex flex-col items-center justify-center h-[50vh] text-slate-500">
                        <Loader2 className="w-8 h-8 animate-spin mb-4 text-blue-500" />
                        <p>Generating tickets from transcript...</p>
                    </div>
                ) : error ? (
                    <div className="text-center p-12 border border-red-900/50 bg-red-900/10 rounded-2xl">
                        <p className="text-red-400">{error}</p>
                        <Button variant="outline" className="mt-4 border-red-800 hover:bg-red-900/20" onClick={() => window.location.reload()}>
                            Retry
                        </Button>
                    </div>
                ) : tickets.length === 0 ? (
                    <div className="text-center p-12 border border-slate-800 bg-slate-900/30 rounded-2xl">
                        <CheckCircle2 className="w-12 h-12 text-slate-600 mx-auto mb-4" />
                        <p className="text-slate-400">No tickets were generated from this meeting.</p>
                    </div>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                        {tickets.map((ticket, i) => (
                            <Card key={i} className="bg-slate-900/50 border-slate-800 backdrop-blur hover:bg-slate-900/80 transition-all group">
                                <CardHeader className="pb-3">
                                    <div className="flex justify-between items-start mb-2">
                                        <Badge variant="outline" className={`capitalize ${getPriorityColor(ticket.priority)} border-0`}>
                                            {ticket.priority || "Normal"}
                                        </Badge>
                                        {ticket.status && (
                                            <span className="text-[10px] uppercase font-bold tracking-wider text-slate-500 bg-slate-950 px-2 py-1 rounded">
                                                {ticket.status}
                                            </span>
                                        )}
                                    </div>
                                    <CardTitle className="text-base font-semibold leading-tight text-slate-200">
                                        {ticket.title || "Untitled Ticket"}
                                    </CardTitle>
                                </CardHeader>
                                <CardContent>
                                    <p className="text-sm text-slate-400 line-clamp-4">{ticket.description}</p>

                                    {(ticket.assignee || ticket.tags?.length) && (
                                        <div className="mt-4 pt-4 border-t border-slate-800/50 flex flex-wrap gap-2">
                                            {ticket.assignee && (
                                                <div className="flex items-center gap-2 text-xs text-slate-300">
                                                    <div className="w-5 h-5 rounded-full bg-blue-600 flex items-center justify-center font-bold text-[10px]">
                                                        {ticket.assignee.charAt(0).toUpperCase()}
                                                    </div>
                                                    {ticket.assignee}
                                                </div>
                                            )}
                                            {ticket.tags?.map(tag => (
                                                <Badge key={tag} variant="secondary" className="text-[10px] px-1.5 h-5 bg-slate-800 text-slate-400 hover:text-white">
                                                    #{tag}
                                                </Badge>
                                            ))}
                                        </div>
                                    )}
                                </CardContent>
                            </Card>
                        ))}
                    </div>
                )}
            </main>
        </div>
    )
}

export default function ScrumBoardPage() {
    return (
        <Suspense fallback={
            <div className="min-h-screen bg-slate-950 flex items-center justify-center">
                <Loader2 className="w-8 h-8 animate-spin text-blue-500" />
            </div>
        }>
            <ScrumBoardContent />
        </Suspense>
    )
}
